<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Focus.RD.BL</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Focus.RD.DataStructs">
      <HintPath>..\..\..\..\..\inetpub\wwwroot\FocusX\bin\Focus.RD.DataStructs.dll</HintPath>
    </Reference>
    <Reference Include="Focus.Common.DataStructs">
      <HintPath>..\..\..\..\..\inetpub\wwwroot\FocusX\bin\Focus.Common.DataStructs.dll</HintPath>
    </Reference>
    <Reference Include="StackExchange.Redis">
      <HintPath>..\..\..\..\..\inetpub\wwwroot\FocusX\bin\StackExchange.Redis.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Practices.EnterpriseLibrary.Data">
      <HintPath>..\..\..\..\..\inetpub\wwwroot\FocusX\bin\Microsoft.Practices.EnterpriseLibrary.Data.dll</HintPath>
    </Reference>
    <Reference Include="Focus.TranSettings.DataStructs">
      <HintPath>..\..\..\..\..\inetpub\wwwroot\FocusX\bin\Focus.TranSettings.DataStructs.dll</HintPath>
    </Reference>
    <Reference Include="System.Data" />
    <Reference Include="Focus.TranSettings.BL">
      <HintPath>..\..\..\..\..\inetpub\wwwroot\FocusX\bin\Focus.TranSettings.BL.dll</HintPath>
    </Reference>
    <Reference Include="Focus.Transactions.DataStructs">
      <HintPath>..\..\..\..\..\inetpub\wwwroot\FocusX\bin\Focus.Transactions.DataStructs.dll</HintPath>
    </Reference>
    <Reference Include="Focus.Transactions.BL">
      <HintPath>..\..\..\..\..\inetpub\wwwroot\FocusX\bin\Focus.Transactions.BL.dll</HintPath>
    </Reference>
    <Reference Include="Focus.Masters.DataStructs">
      <HintPath>..\..\..\..\..\inetpub\wwwroot\FocusX\bin\Focus.Masters.DataStructs.dll</HintPath>
    </Reference>
    <Reference Include="Focus.HRMS.DS">
      <HintPath>..\..\..\..\..\inetpub\wwwroot\FocusX\bin\Focus.HRMS.DS.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml" />
    <Reference Include="Focus.CoreMasters.DataStructs">
      <HintPath>..\..\..\..\..\inetpub\wwwroot\FocusX\bin\Focus.CoreMasters.DataStructs.dll</HintPath>
    </Reference>
    <Reference Include="Focus.Export">
      <HintPath>..\..\..\..\..\inetpub\wwwroot\FocusX\bin\Focus.Export.dll</HintPath>
    </Reference>
    <Reference Include="Focus.Common.BL">
      <HintPath>..\..\..\..\..\inetpub\wwwroot\FocusX\bin\Focus.Common.BL.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="Focus.Pronghorn.BL">
      <HintPath>..\..\..\..\..\inetpub\wwwroot\FocusX\bin\Focus.Pronghorn.BL.dll</HintPath>
    </Reference>
    <Reference Include="Focus.DatabaseFactory">
      <HintPath>..\..\..\..\..\inetpub\wwwroot\FocusX\bin\Focus.DatabaseFactory.dll</HintPath>
    </Reference>
    <Reference Include="Focus.CoreMasters.BL">
      <HintPath>..\..\..\..\..\inetpub\wwwroot\FocusX\bin\Focus.CoreMasters.BL.dll</HintPath>
    </Reference>
    <Reference Include="System.Configuration" />
    <Reference Include="Focus.DataLayer">
      <HintPath>..\..\..\..\..\inetpub\wwwroot\FocusX\bin\Focus.DataLayer.dll</HintPath>
    </Reference>
    <Reference Include="System.Data.DataSetExtensions" />
  </ItemGroup>
</Project>